defaults: &defaults
  consumer_key: AkVhUnNzqyrTG4F6SW3E2Tcp
  consumer_secret: EywLT5BbwcIXWHjVWm63fUnjIwoZz6AZVYoOd8RQ

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults